ktor:
  application:
    modules:
      - koeln.sayer.ApplicationKt.module
  deployment:
    port: 8080
    environment: "$CURRENT_ENV:production"
  posts:
    file_location: "$MD_FILE_LOCATION:/posts"
frontend:
  dev:
    location: "$FRONTEND_DEV_LOCATION:localhost"
    port: "$FRONTEND_DEV_PORT:4200"
